Repository WGBH-MLA/ov-frontend, pull requests merged in 2024-10, with the labels that each got.

#75 🎨 Masterpiece
  app/classes/aapbRecordHelpers.jsx
  app/classes/aapbRecordHelpers.tsx
  app/classes/collectionPresenter.jsx
  app/classes/contentHelpers.jsx
  app/classes/exhibitPresenter.jsx
  app/classes/pageHelpers.jsx
  app/classes/search-ui.tsx
  app/data/aapbBlockTypes.jsx
  app/data/masterpieceData.jsx
  app/data/sidebarTypes.jsx
  app/root.jsx
  app/routes/_index.jsx
  app/routes/collections.$collectionSlug.tsx
  app/routes/collections._index.jsx
  app/routes/collections.masterpiece.jsx
  app/routes/exhibits.$exhibitSlug.tsx
  app/routes/exhibits._index.jsx
  app/routes/preview.tsx
  app/routes/series.jsx
  app/styles/styles.css
  app/types/aapb.tsx
  app/types/pbcore.tsx
  app/utils/fetch.jsx
  app/utils/masterpiece.jsx
  app/utils/preview.jsx
  public/AUDIO_SMALL.png
  public/VIDEO_SMALL.png
Labels: enhancement ➕

#120 🪗 Fixes Organ
  app/routes/catalog.$catalogId.tsx
Labels: bug 🐛, production 🎭

#121 🏡 There's no place like `~`
  app/classes/collectionPresenter.jsx
  app/classes/contentHelpers.jsx
  app/classes/exhibitPresenter.jsx
  app/classes/meta.tsx
  app/classes/openCarousel.jsx
  app/classes/search-ui.tsx
  app/components/Spinner.tsx
  app/routes/_index.jsx
  app/routes/about.jsx
  app/routes/collections.$collectionSlug.tsx
  app/routes/collections._index.jsx
  app/routes/collections.masterpiece.jsx
  app/routes/credits.jsx
  app/routes/exhibits.$exhibitSlug.tsx
  app/routes/exhibits._index.jsx
  app/routes/faq.jsx
  app/routes/preview.tsx
  app/routes/privacy-policy.jsx
  app/routes/search.tsx
  app/routes/series.jsx
  app/routes/terms.jsx
  app/routes/visit-us.jsx
  app/types/openvault.tsx
  app/utils/masterpiece.jsx
  jsconfig.json
  package-lock.json
  package.json
  vite.config.ts
Labels: maintenance 🔧

#123 🍸 Sidebar show/hide + `AAPBRecord` aspect ratio
  app/classes/aapbRecordHelpers.tsx
  app/classes/collectionPresenter.jsx
  app/classes/exhibitPresenter.jsx
  app/classes/pageHelpers.jsx
  app/routes/collections.$collectionSlug.tsx
  app/routes/collections._index.jsx
  app/routes/collections.masterpiece.jsx
  app/styles/styles.css
  app/types/pbcore.tsx
Labels: bug 🐛, enhancement ➕

#128 🏚 Update home
  app/classes/pageHelpers.jsx
  app/routes/_index.jsx
  app/routes/collections._index.jsx
  app/routes/exhibits._index.jsx
  app/styles/styles.css
  app/utils/fetch.jsx
Labels: enhancement ➕
