Repository WGBH-MLA/ov-frontend, pull requests merged in 2024-08, with the labels that each got.

#62 ⚠️ Errors
  Dockerfile
  app/collection.jsx
  app/exhibit.jsx
  app/exhibit_data.jsx
  app/fetch.jsx
  app/root.jsx
  app/styles/styles.css
  package-lock.json
  package.json
Labels: enhancement ➕, production 🎭

#53 ⏰️ Start/End Time For AAPBRecord
  app/classes/aapbRecordHelpers.jsx
  app/classes/collectionPresenter.jsx
  app/classes/contentHelpers.jsx
  app/classes/exhibitPresenter.jsx
  app/classes/openCarousel.jsx
  app/classes/pageHelpers.jsx
  app/collection.jsx
  app/exhibit.jsx
  app/fetch.jsx
  app/root.jsx
  app/routes/_index.jsx
  app/routes/about.jsx
  app/routes/collections.$collectionId.jsx
  app/routes/collections._index.jsx
  app/routes/credits.jsx
  app/routes/exhibits.$exhibitId.jsx
  app/routes/exhibits.$exhibitPath.jsx
  app/routes/exhibits._index.jsx
  app/routes/faq.jsx
  app/routes/help.jsx
  app/routes/privacy_policy.jsx
  app/routes/series.jsx
  app/routes/supportus.jsx
  app/routes/terms.jsx
  app/routes/visitus.jsx
  app/styles/styles.css
  public/backarrow.png
  vite.config.ts
Labels: enhancement ➕

#63 🛣 Redirects
  app/fetch.jsx
  app/root.jsx
  app/routes/catalog.$catalogId.jsx
  app/routes/exhibits.$exhibitPath.jsx
  package-lock.json
  package.json
Labels: enhancement ➕

#67 🎠 Carousel height
  app/classes/openCarousel.jsx
  app/styles/carousel.css
  app/styles/styles.css
  package-lock.json
  package.json
  vite.config.ts
Labels: bug 🐛

#34 🎈 Elasticsearch
  app/classes/navigationBar.jsx
  app/classes/search-ui.tsx
  app/classes/search-utils.jsx
  app/components/AAPBResults.tsx
  app/components/Carousel.tsx
  app/components/Hit.tsx
  app/components/NoResults.tsx
  app/components/NoResultsBoundary.tsx
  app/components/Panel.tsx
  app/components/Refinements.tsx
  app/components/Router.tsx
  app/components/ScrollTo.tsx
  app/components/SearchErrorToast.tsx
  app/components/Spinner.tsx
  app/data/searchkit.json
  app/data/seriesData.jsx
  app/entry.client.jsx
  app/entry.client.tsx
  app/entry.server.tsx
  app/root.jsx
  app/routes/search.tsx
  app/routes/series.jsx
  app/styles/colors.css
  app/styles/search.css
  app/styles/spinner.css
  app/styles/styles.css
  cli.py
  package-lock.json
  package.json
  search/.gitignore
  search/index.html
  search/index.jsx
  search/package-lock.json
  search/package.json
  search/search-ui.jsx
  search/spinner.css
  search/utils.jsx
  search/vite.config.js
  tsconfig.json
  vite.config.ts
Labels: enhancement ➕

#71 🔧 Various CSS Fixes
  app/classes/exhibitPresenter.jsx
  app/classes/pageHelpers.jsx
  app/styles/styles.css
Labels: bug 🐛

#70 📰 Titles
  app/classes/footer.jsx
  app/root.jsx
  app/routes/about.jsx
  app/routes/collections.$collectionId.jsx
  app/routes/collections._index.jsx
  app/routes/credits.jsx
  app/routes/exhibits.$exhibitPath.jsx
  app/routes/exhibits._index.jsx
  app/routes/faq.jsx
  app/routes/help.jsx
  app/routes/privacy_policy.jsx
  app/routes/search.tsx
  app/routes/series.jsx
  app/routes/supportus.jsx
  app/routes/terms.jsx
  app/routes/visitus.jsx
Labels: enhancement ➕

#68 📠 Legacy browsers
  app/root.jsx
  app/routes/faq.jsx
  app/styles/styles.css
  package-lock.json
  package.json
  vite.config.ts
Labels: maintenance 🔧, production 🎭

#74 🗺 Sitemap
  app/classes/footer.jsx
  app/entry.server.tsx
  app/routes/collections.$collectionSlug.tsx
  app/routes/exhibits.$exhibitSlug.tsx
  app/routes/preview.jsx
  app/routes/preview.tsx
  app/routes/privacy-policy.jsx
  app/routes/support-us.jsx
  app/routes/visit-us.jsx
  package-lock.json
  package.json
  public/robots.txt
  vite.config.ts
Labels: production 🎭
