Repository WGBH-MLA/ov-frontend, pull requests merged in 2024-02, with the labels that each got.

#36 👗 Style fixes
  app/styles.css
Labels: bug 🐛, enhancement ➕

#37 👲 Red Hat Fonts
  app/routes/credits.jsx
  app/routes/help.jsx
  app/routes/privacy_policy.jsx
  app/routes/terms.jsx
  app/routes/visitus.jsx
  app/styles.css
  public/fonts/RedHatDisplay-Italic-VariableFont_wght.ttf
  public/fonts/RedHatDisplay-VariableFont_wght.ttf
  public/fonts/RedHatText-Italic-VariableFont_wght.ttf
  public/fonts/RedHatText-VariableFont_wght.ttf
Labels: enhancement ➕

#39 🎨 Colors
  app/classes/collectionPresenter.jsx
  app/classes/contentHelpers.jsx
  app/classes/drawerMenu.jsx
  app/classes/exhibitPresenter.jsx
  app/classes/mobileMenu.jsx
  app/classes/navigationBar.jsx
  app/classes/navigationLink.jsx
  app/classes/openCarousel.jsx
  app/classes/pageHelpers.jsx
  app/root.jsx
  app/routes/about.jsx
  app/routes/collections._index.jsx
  app/routes/credits.jsx
  app/routes/series.jsx
  app/routes/supportus.jsx
  app/styles/carousel.css
  app/styles/colors.css
  app/styles/styles.css
  package.json
Labels: enhancement ➕, maintenance 🔧

#35 Various Fixes
  app/classes/aapbRecordHelpers.jsx
  app/classes/collectionPresenter.jsx
  app/classes/contentHelpers.jsx
  app/classes/drawerMenu.jsx
  app/classes/exhibitPresenter.jsx
  app/classes/mobileMenu.jsx
  app/classes/navigationBar.jsx
  app/classes/navigationLink.jsx
  app/classes/openCarousel.jsx
  app/classes/pageHelpers.jsx
  app/root.jsx
  app/routes/_index.jsx
  app/routes/about.jsx
  app/routes/collections._index.jsx
  app/routes/credits.jsx
  app/routes/help.jsx
  app/routes/privacy_policy.jsx
  app/routes/series.jsx
  app/routes/supportus.jsx
  app/routes/terms.jsx
  app/routes/visitus.jsx
  app/styles/carousel.css
  app/styles/colors.css
  app/styles/styles.css
  package.json
  public/RedHatText-Regular.ttf
  public/fonts/RedHatDisplay-Italic-VariableFont_wght.ttf
  public/fonts/RedHatDisplay-VariableFont_wght.ttf
  public/fonts/RedHatText-Italic-VariableFont_wght.ttf
  public/fonts/RedHatText-VariableFont_wght.ttf
  public/imls.jpg
  public/macfound.jpg
  public/mellon.png
Labels: enhancement ➕
