Repository WGBH-MLA/ov-frontend, pull requests merged in 2025-02, with the labels that each got.

#172 ⛓️ External Links
  app/classes/aapbRecordHelpers.tsx
  app/classes/drawerMenu.jsx
  app/classes/navigationBar.jsx
  app/components/AAPBResults.tsx
  app/components/Results.tsx
  app/components/Series.tsx
  app/components/Suggestions.tsx
  app/root.jsx
  app/routes/_index.jsx
  app/routes/about.jsx
  app/routes/catalog._index.tsx
  app/routes/collections.$collectionSlug.tsx
  app/routes/collections.masterpiece-funders.jsx
  app/routes/collections.masterpiece.jsx
  app/routes/exhibits.$exhibitSlug.tsx
  app/routes/miniseries.$miniseriesId.jsx
  app/routes/search.tsx
  app/routes/series.jsx
  app/styles/search.css
  app/styles/styles.css
  app/utils/fetch.jsx
  jsconfig.json
  public/AUDIO_SMALL.png
  public/VIDEO_SMALL.png
  public/down-chevron-small.png
  public/forbidden.png
  public/magnifying_glass.png
  public/menu-white.png
  public/menu.png
Labels: maintenance 🔧

#193 🚑 `/health` route
  app/routes/health.tsx
Labels: maintenance 🔧, production 🎭

#197 🫖 Teapot
  app/routes/_index.jsx
  app/routes/catalog._index.tsx
Labels: breaking 💔, production 🎭

#195 Add Extended Credits Pages, Reorder UI Elements
  app/classes/exhibitPresenter.tsx
  app/classes/navigationBar.jsx
  app/classes/openCarousel.jsx
  app/classes/pageHelpers.jsx
  app/components/Help.tsx
  app/routes/_index.jsx
  app/routes/collections.masterpiece-funders.jsx
  app/routes/credits._index.jsx
  app/routes/credits.march-on-washington.jsx
  app/routes/credits.new-television-workshop.jsx
  app/routes/credits.openvault.jsx
  app/routes/credits.research.jsx
  app/routes/credits.rock-and-roll.jsx
  app/routes/credits.say-brother.jsx
  app/routes/credits.ten-oclock-news.jsx
  app/routes/credits.the-advocates.jsx
  app/routes/credits.vietnam.jsx
  app/routes/credits.war-and-peace-in-the-nuclear-age.jsx
  app/routes/faq.jsx
  app/styles/carousel.css
Labels: bug 🐛, production 🎭
