Repository WGBH-MLA/ov-frontend, pull requests merged in 2025-01, with the labels that each got.

#152 🔐 Access Levels Option
  app/classes/aapbRecordHelpers.tsx
  app/classes/collectionPresenter.tsx
  app/classes/contentHelpers.jsx
  app/classes/exhibitPresenter.tsx
  app/routes/collections.masterpiece.jsx
  app/routes/exhibits.$exhibitSlug.tsx
  app/styles/styles.css
  app/types/aapb.tsx
  app/types/openvault.tsx
  app/utils/fetch.jsx
  public/document.png
  public/forbidden.png
  public/other.jpg
  public/other.png
Labels: enhancement ➕

#162 🔙 PBCore backslashes
  app/data/pbcore_xml_to_json.jsx
Labels: bug 🐛, production 🎭

#179 🖌 Update Masterpiece
  app/classes/aapbRecordHelpers.tsx
  app/classes/pageHelpers.jsx
  app/components/UnderConstruction.tsx
  app/data/masterpieceData.jsx
  app/data/masterpieceFlavor.jsx
  app/root.jsx
  app/routes/_index.jsx
  app/routes/collections._index.jsx
  app/routes/collections.masterpiece-funders.jsx
  app/routes/collections.masterpiece.jsx
  app/routes/faq.jsx
  app/routes/miniseries.$miniseriesId.jsx
  app/styles/styles.css
  package-lock.json
  package.json
Labels: maintenance 🔧, production 🎭
